language: go
arch:
    - amd64
    - ppc64le
go:
  - "1.11"
  - "1.12"
  - "1.13"
before_install:
  - go get github.com/xeipuuv/gojsonreference
  - go get github.com/xeipuuv/gojsonpointer
  - go get github.com/stretchr/testify/assert
  
matrix:
  allow failures:
              - go: "1.11"
              - go: "1.12"
